### ISSUE TITLE
Implicit grant type

### ISSUE THREAD

**Issue by iamdriz** [thomseddon/cakephp-oauth-server#50]
Apparently this plugin doesn't support the implicit grant type...

And according to this issue: https://github.com/thomseddon/cakephp-oauth-server/pull/35 here, there were/are plans to add this grant type to the plugin.

Is this still the case?

**Comment by iamdriz** [comment]
@thomseddon Actually it turns out this plugin DOES support the implicit grant type.

By doing:

`http://server.com/oauth/authorize?response_type=token&client_id=NTEzN2FjNzZlYzU4ZGM2&state=123`

It then returns:

`http://client.com/?state=123#access_token=96ccd42474dc45185ee3a4afa63481fa1effaea1&expires_in=3600&token_type=bearer&scope=&refresh_token=b842af679944c2cb234b1b02eacfec36d54096bb`

**Comment by grizzly** [comment]
Ich bin bis einschließlich 21 Juni 2015 auf Urlaub und daher in dieser Zeit nicht erreichbar.
I am out of office until 21th of June 2015.

Die eMails werden nicht automatisch weitergeleitet.
The emails will not be forwarded.
 
Mit freundlichen Grüßen / Kind regards

Stefan Mayr
