### ISSUE TITLE
clients should maybe better be auth_clients

### ISSUE THREAD

**Issue by dereuromark** [thomseddon/cakephp-oauth-server#52]
Looking at

    DROP TABLE IF EXISTS `clients`;
    CREATE TABLE `clients` (...)

This can easily create a collision with an existing app `clients` table when integrating OAuth2 here.

So maybe your plugin's table should better be `auth_clients` and also then closer to the `auth_codes` table then. `access_tokens` and `refresh_tokens` sound unique enough to not run into collisions that easily.

**Comment by rchavik** [comment]
Similar to #24
