### ISSUE TITLE
Plans for CakePHP3?

### ISSUE THREAD

**Issue by dereuromark** [thomseddon/cakephp-oauth-server#58]
Any plans for OAuth(2) and CakePHP3?
Like upgrade this one? Or rather write new from scratch etc?

What would be the things to be learned from the current plugin and what to improve maybe?

Or maybe just wrap https://github.com/thephpleague/oauth2-server / https://github.com/thephpleague/oauth2-client ?

**Comment by rchavik** [comment]
cc @dakota

**Comment by dakota** [comment]
We already have a working (but short on unit tests) implementation of https://github.com/thephpleague/oauth2-server. Currently not publicly available, but I'll start the process on my side to get it out there.

**Comment by dereuromark** [comment]
OK, cool.
Maybe we can help with the tests or alike.
So if you could open a branch or sth we can take a look in the very near future :)
Thank you.

**Comment by burzum** [comment]
I'm interested in a 3.x version as well. :)

**Comment by klickagent** [comment]
same interest here. if you need any help open a branch for it.

**Comment by blieb** [comment]
Sounds great, Need support for oauth in my cakephp3 project. When will we see the first version/beta?

**Comment by dakota** [comment]
You should hopefully see it today still! Otherwise, Monday.

**Comment by blieb** [comment]
Ok thank you for the update, then I will wait for it instead of making my own ;)

**Comment by dakota** [comment]
Done! https://github.com/uafrica/oauth-server

Not on packagist just yet, but will be soon.

**Comment by thomseddon** [comment]
:+1: I think @dakota 's plugin may be the way to go, if others agree I will formally depreciate this module in favour of that

**Comment by burzum** [comment]
I'm OK with this plugin except that I don't like the fact that it requires three other modules (crud, crud-ui, bootstrap-ui) that aren't really in the scope of OAuth.

**Comment by thomseddon** [comment]
Hmm good point...

**Comment by dakota** [comment]
@burzum Using CrudView for the interface for creating clients and scopes. Do you think it would be better without an interface built in? Or maybe make those packages suggests rather than requires?

**Comment by burzum** [comment]
@dakota I would prefer if they're suggested but not a hard requirement.

**Comment by rchavik** [comment]
@burzum It's already been taken out by dakota

**Comment by burzum** [comment]
@rchavik excellent thank you!

**Comment by thomseddon** [comment]
FYI, I've now marked this project as unmaintained and linked to @uafrica's project
